### ISSUE TITLE
It's 2017, give us ethnicity options

### ISSUE THREAD

**Issue by pwd-github** [makegirlsmoe/makegirlsmoe_web#17]
Can we get the ability to create black girls?

**Comment by Aixile** [comment]
If you provide us training images of 2d black girls, we might help you build a CycleGAN and turn every girl into black.

**Comment by sabret00the** [comment]
Here's some: http://www.fanpop.com/clubs/anime/answers/show/391632/dark-skinned-female-anime-characters-please

**Comment by alucard0134** [comment]
>40 images

ye-no

**Comment by Aixile** [comment]
The latest version includes an option called 'Dark Skin', but this attribute does not always work due to the unbalanced training dataset.  You can use 'Advanced Mode' and set 'Dark Skin' tag to 2~3 or higher, the generator can produce black girls easier.
