### ISSUE TITLE
文字列でノイズをインポート/エクスポートする機能が欲しい

### ISSUE THREAD

**Issue by kgtkr** [makegirlsmoe/makegirlsmoe_web#26]
画像より文字列の方が共有が便利な事もあるので

**Comment by Aixile** [comment]
エキスパートモードのExport Options を使えば、文字列ノイズを含めるJSONファイルにセーブできます

**Comment by kgtkr** [comment]
そのような機能があったんですね。気づきませんでした。ありがとうございます
