### ISSUE TITLE
Strange result from the noise seed.

### ISSUE THREAD

**Issue by strangedoll** [makegirlsmoe/makegirlsmoe_web#27]
![default](https://user-images.githubusercontent.com/32530649/31207232-9658e3ea-a9af-11e7-8a9e-777c66dc9cc1.png)
![default](https://user-images.githubusercontent.com/32530649/31207236-9c24d6bc-a9af-11e7-8407-3512bdf6e003.png)
![default](https://user-images.githubusercontent.com/32530649/31207241-a1ef7c50-a9af-11e7-859c-2d35af57ccea.png)
![default](https://user-images.githubusercontent.com/32530649/31207244-a7fc35e8-a9af-11e7-8ec5-512c017fd0e1.png)
![default](https://user-images.githubusercontent.com/32530649/31207246-ac92540c-a9af-11e7-9ca4-425fface5351.png)
![default](https://user-images.githubusercontent.com/32530649/31207251-b267c5d8-a9af-11e7-9082-e9186c414415.png)
![default](https://user-images.githubusercontent.com/32530649/31207253-b820ef72-a9af-11e7-867b-ff0b5694cee4.png)

**Comment by zhangjk95** [comment]
Please specify what is strange about the results and your original expectation.
