### ISSUE TITLE
Clarification about the generator archetecture

### ISSUE THREAD

**Issue by appierys** [makegirlsmoe/makegirlsmoe_web#29]
Hi,

Thanks for your contribution. I am just curious about the architecture. In the original SRResNet, after the residual blocks, there was `CONV`, `BN`, `ELEMENTWISE-SUM`.
![SRGAN](https://raw.githubusercontent.com/zsdonghao/SRGAN/master/img/model.jpeg)

However, in your paper you seems to use `CONV`, `BN`, `ReLU`, `ELEMENTWISE-SUM`. Is there any reason why `ReLU` is inserted?

BTW, https://arxiv.org/pdf/1708.05509.pdf shows `BN`, `ReLU`, `ELEMENTWISE-SUM`, which seems to be a mistake.

**Comment by Aixile** [comment]
`CONV, BN, ReLU, ELEMENTWISE-SUM` is used in my code, this might be my fault when I wrote SResNet.
But I think whether adding this `ReLu`  or not won't change the performance.
