### ISSUE TITLE
Provide up-to-date links to the data set

### ISSUE THREAD

**Issue by AliengirlLiv** [makegirlsmoe/makegirlsmoe_web#33]
Following [this paper](https://makegirlsmoe.github.io/assets/pdf/technical_report.pdf), we tried to obtain the data set through a sql query to http://erogamescape.dyndns.org/~ap2/ero/toukei_kaiseki/sql_for_erogamer_form.php.  Unfortunately, our requests all seem to time out.  Has the link moved? Is there a way to get step-by-step instructions on how to obtain the data set?

**Comment by Aixile** [comment]
No, this website has blocked all requests outside Japan.
Please reference https://github.com/shaform/GirlsManifold/ for the dataset.
